# ******************************************************************************
# * Copyright (c) 2023 DevCloud Software. All Rights reserved.
# ******************************************************************************
general:
  locale: de_DE
api:
  port: 8080